Added some debug stuff and the more verbose SHH error handling

diff --git a/ec2_backup b/ec2_backup
--- a/ec2_backup
+++ b/ec2_backup
@@ -51,6 +51,19 @@ usage() {
 echo "ec2_backup [-h] [-m method] [-v volume-id] dir "
 } 
 
+
+errorTerminate() {
+        if [ ! -z "$instance" ]; then
+                aws ec2 terminate-instances --instance-ids $instance >/dev/null
+        fi
+
+        if [ ! -z "$volume" ] && [ $f_uservol -eq 0 ] ; then
+                aws ec2 delete-volume --volume-id $volume >/dev/null
+        fi
+
+}
+
+
 #get the size and status of the volume
 #the volume id is passed as the first and only argument
 getVolumeStatus() {
@@ -94,7 +107,6 @@ volumeWait() {
 		echo "Volume initializing..."
 	fi
         while [[ "$volumeStatus" != *"available"* ]]; do
-p
                 getVolumeStatus $volume
 		sleep 1
 		if [ $f_debug -eq 1 ]; then
@@ -318,24 +330,22 @@ while [[ "$instanceState" != "running" ]]; do
                 sleep 1
         done
 
+if [ $f_debug -eq 1]; then
+	echo "Instance ID: $instance "
+fi
 #Extra sleep to make sure that the instance has more time to boot up before ssh wait happends
 sleep 3
 }
 
 terminateInstance() {
+
+if [ $f_debug -eq 1]; then
+        echo "Cleaning up instnce: $instance "
+fi
+
 aws ec2 terminate-instances --instance-ids $instance >/dev/null
 }
 
-errorTerminate() {
-	if [ ! -z "$instance" ]; then
-		aws ec2 terminate-instances --instance-ids $instance >/dev/null
-	fi
-
-	if [ ! -z "$volume" ] && [ $f_uservol -eq 0 ] ; then
-		aws ec2 delete-volume --volume-id $volume >/dev/null	
-	fi
-
-}
 
 getHostname(){
 
@@ -434,7 +444,8 @@ exit
 " 2>&1`
 
 if [ $? -gt 0 ]; then
-	echo "$var" 1>&2;
+	echo "Failed to SSH to create filesystem: $var" 1>&2;
+	errorTerminate
 	exit 1;
 fi
 
